version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.14

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
          name: "Instal dependencies"
          command: "npm install"
      - run:
          name: "Build static assets"
          command: "npm run build"

      # Save the built repo
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app
  compile:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.14
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "compile app"
          command: "npm run compile"

  beta-deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.14
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: "Deploy to beta"
          command: "npm run upload beta"
workflows:
  build-compile-and-deploy:
    jobs:
      - build
      - compile
      - hold:
          type: approval
          requires:
            - build
            - compile
      - beta-deploy:
          name: "deploy to beta"
          context: secrets
          requires:
            - hold
      # - deploy:
      #   name: "deploy to production"
      #   context: secrets
      #   requires:
      #     - beta-deploy
      #   filters:
      #     branches:
      #       only: master
