version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.15

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
          name: "Instal dependencies"
          command: "npm install"
      - run:
          name: "Build static assets"
          command: "npm run build"

      # Save the built repo
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app
  compile:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.15
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "compile app"
          command: "npm run compile"

  beta-deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.15
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: "Deploy to beta"
          command: "npm run upload beta"

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.15
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: "Deploy to production"
          command: "npm run upload"
workflows:
  build-compile-and-deploy:
    jobs:
      - build
      - compile:
          requires:
            - build
      - beta-deploy:
          context: secrets
          requires:
            - compile
          filters:
            branches:
              ignore: master
              only: /beta-.*/
      - deploy:
          context: secrets
          requires:
            - compile
          filters:
            branches:
              only: master
